<?xml version="1.0" encoding="utf-8"?><Database Name="20131011110029" Class="CompromissoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=valera;Initial Catalog=20131011110029;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="_20131011110029ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Compromisso" Member="Compromissos">
    <Type Name="Compromisso">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="local" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="data" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="realizado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>